### ISSUE TITLE
Documentation Request: Different Language

### ISSUE THREAD

**Issue by SumNeuron** [elisiondesign/vue-code-highlight#11]
The docs currently just say that we have to import the prism files, but how do we change the class?

**Comment by SumNeuron** [comment]
You should mention in the docs that you expose a property: `language`
https://github.com/elisiondesign/vue-code-highlight/blob/master/src/CodeHighlight.vue#L13

**Comment by i-break-codes** [comment]
This should be mentioned in the docs, I was going crazy to find a solution.. a default set of config will be helpful

**Comment by honzabilek4** [comment]
Thanks, I've updated README. Just let me know if you find sth else.
