### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by matthew-white** [elisiondesign/vue-code-highlight#18]
I'm noticing that this repository lists the MIT license, but npm lists ISC as the license. My understanding is that these are similar licenses, but I think it'd be helpful for there to be consistency. Vue itself uses the MIT license, so between the two, I think the MIT license might be preferable.

**Comment by honzabilek4** [comment]
I'll update the package.json with MIT.

**Comment by honzabilek4** [comment]
Fixed in v0.7.6
