### ISSUE TITLE
beforeUpdate Error when using dynamic content

### ISSUE THREAD

**Issue by timv256** [elisiondesign/vue-code-highlight#19]
I'm a little new to Vue, but I'm having this problem when content is updating and the beforeUpdate method gets called, it encounters undefined text and this stops working. Any tips on what I'm doing wrong or is this a bug?

vue-code-highlight language="sql"
              pre
                  {{selectedValue.QueryString}}

beforeUpdate: function beforeUpdate() {
    var newText = this.$slots.default[0].text.replace(/^[\r\n\s]*|[\r\n\s]*$/g, '');
    this.$el.querySelector('code').textContent = newText;
    Prism.highlightAllUnder(this.$refs.codeBlock);

TypeError: Cannot read property 'replace' of undefined
    at VueComponent.beforeUpdate (vue-code-highlight.esm.js?fb0e:788)
    at invokeWithErrorHandling (vue.esm.js?bcea:1863)
    at callHook (vue.esm.js?bcea:4228)
    at Watcher.before (vue.esm.js?bcea:4085)
    at flushSchedulerQueue (vue.esm.js?bcea:4315)
    at Array.eval (vue.esm.js?bcea:1989)
    at flushCallbacks (vue.esm.js?bcea:1915)

**Comment by honzabilek4** [comment]
Hello @timv256, could you please create a codesanbox which reproduces your issue? I'll be happy to look into it.

**Comment by timv256** [comment]
I decided to just use the prism editor since I want users to edit the SQL, so I got it working with that component. Also, my setup has a ton of external libraries and is using typescript, so it could be something messing it up anyway. Thanks for your willingness to help anyway!

**Comment by erickfabiandev** [comment]
Query I want to make my component editable but I still can't do it, could you help me
