### ISSUE TITLE
Does not work on Vue CLI 3

### ISSUE THREAD

**Issue by elalienx** [elisiondesign/vue-code-highlight#2]
Hi, any idea on how to make this work on the new Vue CLI 3.0?

I am using Typescript on that CLI build. 

Cheers and thanks for you attention.

**Comment by elalienx** [comment]
Hi, I answered my own question. If anyone has the same problem the solution is here: 
https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

Follow the instructions explained by Retsam

**Comment by honzabilek4** [comment]
Thanks!
