### ISSUE TITLE
Unable to update the highlighted content

### ISSUE THREAD

**Issue by vicpon** [elisiondesign/vue-code-highlight#4]
There's no support for re-highlighting the content dynamically. I have fixed it outside of the component, but I'll create a PR to fix this in the main repo.

**Comment by vicpon** [comment]
Fixed in [https://github.com/elisiondesign/vue-code-highlight/pull/5/commits/eb582611d3012df416dfcec15e59adf23a1b5a24](url)

**Comment by honzabilek4** [comment]
Hi, thanks for the PR. I'm merging it asap.

**Comment by honzabilek4** [comment]
I merged the PR and removed the demo, since it's not needed. I will add some note to readme instead.
