### ISSUE TITLE
No highlighting for other languages

### ISSUE THREAD

**Issue by basselAhmed** [elisiondesign/vue-code-highlight#6]
Thanks for this awesome component!

But I found a small issue here, please check this sandbox
https://codesandbox.io/s/codesandbox-nuxt-m0h4f

I've checked other issues here discussing the same thing but it still doesn't seem to be working, only javascript works atm.

**Comment by basselAhmed** [comment]
nvm I just had to include the languages I need like so
```js
import 'prism-es6/components/prism-c'
import 'prism-es6/components/prism-objectivec'
```

**Comment by honzabilek4** [comment]
Hey,
Thanks for this issue. This is not your fault. I'll try to modify the readme or the `prism-es6` module, to make the setup more intuitive.
