### ISSUE TITLE
Question: linenumbers copy

### ISSUE THREAD

**Issue by nielsnuebel** [elisiondesign/vue-code-highlight#9]
Short Question: 

Can I use line Numbers Plugin and Copy Plugin from prism. And if yes how?  

I use reactive code and build a Plattform for Code Snippets (google Analytics, etracker, Facebook Pixel aso.). 
1. Visitor choose a snippet 
2. a new form loaded
3. While fill inputs the snippet generate
4. Copy the result 
5. And past it into the website head for example.

**Comment by honzabilek4** [comment]
Hello,
Sorry, your question got lost in tons of GitHub notifications I'm receiving. 
Did you already find answer to your question?
